Repository BuildForSDGCohort2/Team-254-zaoBora-frontend, pull requests merged in 2020-09, with the labels that each got.

#7 Setup server side rendering
  .gitignore
  README.md
  package.json
  public/index.html
  server/index.js
  src/App.js
  src/App.scss
  src/components/LoginForm.js
  src/components/NavBar.js
  src/components/RegisterForm.js
  src/index.js
  src/pages/About.js
  src/pages/Login.js
  src/pages/Register.js
  src/routers/AppRouter.js
  src/store/configureStore.js
  src/styles/components/_navbar.scss
  src/tests/App.test.js
  src/utils/validate.js
  webpack.config.js
  webpack.server.js
  yarn.lock
Labels: documentation

#14 Cart page
  src/App.scss
  src/components/Header.js
  src/pages/Cart.js
  src/pages/Checkout.js
  src/pages/Market.js
  src/routers/AppRouter.js
  src/styles/base/_settings.scss
  src/styles/pages/_cart.scss
Labels: enhancement

#17 Started Content Writing
  src/pages/About.js
Labels: documentation

#16 Ft google auth
  package-lock.json
  package.json
  src/auth_config.js
  src/buttons/google/GoogleButton.js
  src/buttons/google/GoogleLogoutButton.js
  src/components/LoginForm.js
  src/components/RegisterForm.js
  src/index.js
Labels: enhancement

#18 Ft user account page
  src/App.scss
  src/components/AccountMenu.js
  src/components/AccountProfileForm.js
  src/components/Header.js
  src/components/MobileNav.js
  src/components/Orders.js
  src/pages/Account.js
  src/pages/AccountOrders.js
  src/pages/Cart.js
  src/pages/FAQ.js
  src/routers/AppRouter.js
  src/styles/base/_base.scss
  src/styles/components/_account-menu.scss
  src/styles/components/_account-profile-form.scss
  src/styles/components/_header.scss
  src/styles/components/_orders.scss
  src/styles/pages/_account.scss
  src/utils/validate.js
Labels: enhancement

#19 Ch frontend deploy
  package-lock.json
  package.json
  src/pages/Cart.js
  yarn.lock
Labels: enhancement

#20 Ft farmers dashboard page
  src/App.scss
  src/components/AccountProfileForm.js
  src/components/Header.js
  src/components/LoginForm.js
  src/components/ResetPasswordForm.js
  src/components/farmer/FarmerHeader.js
  src/components/farmer/FarmerPostList.js
  src/components/farmer/FarmersDashboardMenu.js
  src/components/farmer/FarmersOrdersList.js
  src/components/farmer/FarmersProfile.js
  src/components/farmer/NewPostForm.js
  src/components/farmer/ResetFarmersPassword.js
  src/pages/FAQ.js
  src/pages/farmer/FarmerResetPassword.js
  src/pages/farmer/FarmersDashboard.js
  src/pages/farmer/FarmersOrders.js
  src/pages/farmer/FarmersPosts.js
  src/pages/farmer/FarmersResetPassword.js
  src/routers/AppRouter.js
  src/setupTests.js
  src/styles/base/_settings.scss
  src/styles/components/_header.scss
  src/styles/components/_reset-password.scss
  src/styles/components/farmer/_farmer-header.scss
  src/styles/components/farmer/_farmer-menu.scss
  src/styles/components/farmer/_farmer-order-list.scss
  src/styles/components/farmer/_farmer-post-list.scss
  src/styles/components/farmer/_farmer-profile.scss
  src/styles/pages/farmer/_farmers-dashboard.scss
  src/tests/App.test.js
  src/utils/validate.js
Labels: enhancement

#21 Built responsive product item page
  src/App.scss
  src/components/ItemListStyle.js
  src/components/ProductItemReviews.js
  src/pages/Market.js
  src/pages/ProductItem.js
  src/routers/AppRouter.js
  src/styles/components/_header.scss
  src/styles/components/_product-item-review.scss
  src/styles/pages/_market.scss
  src/styles/pages/_product-item.scss
Labels: enhancement

#26 Ft checkout page
  src/App.scss
  src/assets/mpesa.png
  src/assets/royparcel.png
  src/components/AccountProfileForm.js
  src/components/CheckoutForm.js
  src/components/Header.js
  src/components/RegisterForm.js
  src/pages/Checkout.js
  src/styles/pages/_checkout.scss
Labels: enhancement

#22 Commented out all console.log on login and register forms
  src/components/LoginForm.js
  src/components/RegisterForm.js
Labels: bug

#27 created actions folder, reducer folder, register actions and connecte…
  src/actions/authentication.js
  src/actions/types.js
  src/components/LoginForm.js
  src/components/RegisterForm.js
  src/reducers/login.js
  src/reducers/register.js
  src/reducers/rootReducers.js
  src/store/configureStore.js
Labels: enhancement

#29 Ft products filter
  README.md
  src/.env.example
  src/App.scss
  src/actions/filters.js
  src/actions/orders.js
  src/actions/products.js
  src/assets/famer.jpg
  src/components/CheckoutForm.js
  src/components/FilterProductItem.js
  src/components/FilterProducts.js
  src/components/Header.js
  src/components/ItemListStyle.js
  src/components/LoginForm.js
  src/components/MobileNav.js
  src/components/Orders.js
  src/components/ProductItemReviews.js
  src/components/RegisterForm.js
  src/components/farmer/FarmerHeader.js
  src/components/farmer/FarmersOrdersList.js
  src/pages/Account.js
  src/pages/AccountOrders.js
  src/pages/Cart.js
  src/pages/Checkout.js
  src/pages/Login.js
  src/pages/Market.js
  src/pages/ProductItem.js
  src/pages/Register.js
  src/reducers/filters.js
  src/reducers/orders.js
  src/reducers/products.js
  src/reducers/rootReducers.js
  src/selectors/orders.js
  src/selectors/products.js
  src/styles/components/_filter-products.scss
  src/styles/components/_header.scss
  src/styles/components/_mobile-nav.scss
  src/styles/pages/_account.scss
  src/styles/pages/_market.scss
  src/utils/CookieStorage.js
Labels: bug, enhancement

#30 Connected cart with redux
  src/actions/authentication.js
  src/actions/cart.js
  src/actions/types.js
  src/components/Header.js
  src/pages/Checkout.js
  src/pages/ProductItem.js
  src/reducers/cart.js
  src/reducers/rootReducers.js
  src/utils/Constants.js
Labels: enhancement

#34 Added email verification component
  .env.example
  src/App.scss
  src/actions/authentication.js
  src/components/RegisterForm.js
  src/components/farmer/NewPostForm.js
  src/pages/EmailVerification.js
  src/pages/Register.js
  src/routers/AppRouter.js
  src/styles/pages/_email-verification.scss
  src/utils/validate.js
Labels: enhancement

#35 Ft authentication
  src/App.js
  src/actions/authentication.js
  src/actions/resMsg.js
  src/actions/types.js
  src/components/Header.js
  src/components/LoginForm.js
  src/components/RegisterForm.js
  src/index.js
  src/pages/Account.js
  src/pages/Login.js
  src/pages/Market.js
  src/pages/ProductItem.js
  src/pages/Register.js
  src/reducers/authentication.js
  src/reducers/login.js
  src/reducers/register.js
  src/reducers/resMsg.js
  src/reducers/rootReducers.js
  src/styles/pages/_register.scss
  src/utils/Common.js
  src/utils/Constants.js
  src/utils/CookieStorage.js
Labels: documentation
